%YAML 1.2
---
  - name: Kubernetes cluster preflight checklist
    hosts: all
    roles:
      - kubernetes-preflight

  - name: Install and configure the Kubernetes master
    hosts: master
    roles:
      - kubernetes-master

  - name: Install and configure etcd
    hosts: etcd
    roles:
      - kubernetes-etcd

  - name: Install and configure the Kubernetes nodes
    hosts: node
    roles:
      - kubernetes-node
...
